openapi: 3.0.2
info:
  title: Bounty Service API
  description: API for managing bug bounties and claims (MVP)
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /bounties:
    get:
      summary: Retrieve a list of all bounties
      responses:
        '200':
          description: List of bounties
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bounty'
  /bounties/{id}:
    get:
      summary: Retrieve a single bounty by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Single bounty
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bounty'
    patch:
      summary: Update a single bounty by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BountyUpdate'
      responses:
        '200':
          description: Updated bounty
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bounty'
  /bounties/{id}/submit-fix:
    post:
      summary: Submit a fix for a single bounty by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FixSubmission'
      responses:
        '201':
          description: Fix submitted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bounty'
components:
  schemas:
    Bounty:
      type: object
      properties:
        id:
          type: string
          description: Unique ID of the bounty
        title:
          type: string
          description: Title of the bounty
        description:
          type: string
          description: Description of the bounty
        points:
          type: integer
          description: Number of points for solving the bounty
    BountyUpdate:
      type: object
      properties:
        id:
          type: string
          description: Unique ID of the bounty (read-only)
        title:
          type: string
          description: Title of the bounty (optional)
        description:
          type: string
          description: Description of the bounty (optional)
        points:
          type: integer
          description: Number of points for solving the bounty (optional)
    FixSubmission:
      type: object
      properties:
        fix:
          type: string
          description: The actual fix submitted by the user
        proof:
          type: string
          description: Proof of the fix, such as a screenshot or video
  responses:
    '400': {description: Bad request}
    '401': {description: Unauthorized}
    '403': {description: Forbidden}